Feature lp 33 leaderboard api
incubyte/learning-planner pull request #25
Opened 2023-04-28 10:02 UTC by Charvit123

## What

Please include a summary of the changes.

- [x] Added item
- [ ] Updated item

## How

- Change x to y
- Update foo logic

## Why

Why were these changes made?

- Item was missing
- Item needed changes

## Screenshots (If applicable)

Please include any relevant screenshots that may help explain the change.

## Notes

Notes about the change, if any.

# Checklist

- [ ] My code follows the style guidelines of this project and is properly formatted
- [ ] I have performed a self-review of my own changes
- [ ] All existing tests pass, and I have added new ones if required

2023-05-01 06:48 UTC, abdulkalam1233 requested changes

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/src/user/user.service.ts
> +              id: currentUserCourse.userId,
use:  user_id: {
      in: users.map(user => user.user_id)
    },
Avoid making DB calls in loops

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/test/user.e2e-spec.ts
> +    expect(response.status).toBe(200);
Data length check is missing

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/test/user.e2e-spec.ts
>      expect(response.status).toBe(200);
Add data assertion

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/src/user/user.service.ts
> +        where: { userId: userid, isCompleted: true },
Make this query dynamic based on the status

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/src/user/user.service.spec.ts
use https://www.npmjs.com/package/jest-mock-extended

2023-05-01 06:48 UTC, abdulkalam1233 commented on backend/src/user/user.service.spec.ts
const PrismaServiceMockFactory = {
  provide: PrismaService,
  useFactory: mockDeep(PrismaService),
};

2023-05-03 06:58 UTC, Charvit123 commented on backend/src/user/user.service.spec.ts
@abdulkalam1233 we have tried to use this deepmock but we are getting the same errors of circular dependency at three other places.

2023-05-04 07:08 UTC, merged